(*WRITE A PROGRAM TO GET THE SUM OF ODD NUMBERS PRESNT IN NUMBER BLOCK*)

MVI C,04H
LXI H,2050H
MVI B,00H
LOOP2:MOV A,M
      ANI 01H
      JZ LOOP
      MOV A,B
      ADD M
      MOV B,A
LOOP:INX H
     DCR C
     JNZ LOOP2
     MOV A,B
     STA 2055H
     HLT
