(*WRITE A PROGRAM TO FIND THE MAXIMUM NUMBER FROM GIVEN NUMBER OF BLOCK*)

MVI C,04H
LXI H,2050H
MOV A,M
DCR C
LOOP2:INX H
      MOV B,M
      CMP B
      JNC LOOP
      MOV A,B
LOOP:DCR C
     JNZ LOOP2
     STA 2055H
     HLT
